version: '3'
services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: everytime
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config:/etc/mysql/conf.d
      - ./db/init/:/docker-entrypoint-initdb.d

  web:
    image: everytime
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      mysql_host: root
