services:
  web:
    container_name: spring
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      mysql_host: db
    restart: always
    volumes:
      - app:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: spring_everytime
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    restart: always

volumes:
  dbdata:
  app: