spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/ceos?createDatabaseIfNotExist=true
    username: root
    password: 162534Qwe!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true