spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

logging:
  level:
    org.hibernate.SQL: debug
  #  org.hibernate.type: trace

file:
  dir: E:\CEOS FILE\spring-everytime-19th\attachment_file\

jwt:
  token:
    secret: ${JWT_TOKEN_SECRET}  # 실제로 사용하는 비밀키는 환경변수로 로컬에 저장.(노출 방지)
    expireAccessTokenTimeMs: 3600000 # 1 hour
    expireRefreshTokenTimeMs: 604800000 # 7 days