spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:local;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: Ab016018!@
  jpa:
    show_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
      format_sql: true