# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: make application.yml

      - run: mkdir ./src/main/resources
      - run: touch ./src/main/resources/application.yml
      - run: echo "${{ vars.DEV_APPLICATION }}" > ./src/main/resources/application.yml
      - run: cat ./src/main/resources/application.yml


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Execute Gradle build
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: build and release to DockerHub
        env:
          NAME: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DEV_BACKEND_APP_NAME }}
        run: |
          docker build -t $NAME/$APP -f ./Dockerfile . 
          docker push $NAME/$APP

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        env:
          NAME: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DEV_BACKEND_APP_NAME }}
          COMPOSE: docker-compose.yml
        with:
          username: ubuntu
          host: ${{ secrets.UBUNTU_DEV_HOST }}
          key: ${{ secrets.UBUNTU_DEV_KEY }}
          envs: APP, COMPOSE, NAME
          script_stop: true
          script: |
            sudo docker-compose -f $COMPOSE down --rmi all
            sudo docker pull $NAME/$APP
            sudo docker-compose -f $COMPOSE up -d