name: Deploy Development Server

## parking0 브랜치에 push되면 실행
on:
  push:
    branches: [ "parking0" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      ## 여러분이 사용하는 버전을 사용하세요
      - name: Set up JDK 17           # 가상환경에 JDK 17 세팅하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## 1. gradle build
      - name: Build with Gradle
        run: ./gradlew build

      # 2. 도커 이미지 만들기 & push
      - name: Build Docker Image & push
        run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/spring .
            docker push ${{ secrets.DOCKER_USERNAME }}/spring

      # 3. 원격 접속 & 이미지 pull & 컨테이너 생성
      - name: Remote SSH & Pull Image & Run Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}      
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/spring:0.1
            docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/spring:0.1
            docker image prune -a -f